// <auto-generated />
using BotanicalAdventure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BotanicalAdventure.Migrations
{
    [DbContext(typeof(BotanicalAdventureContext))]
    partial class BotanicalAdventureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BotanicalAdventure.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Difficulty")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Edible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EdibleDesc")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Found")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Habitat")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Hint")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("History")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Latin")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Picture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Smell")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Symbolism")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Taste")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Category = "Forest",
                            Description = "These illusive mushrooms range from light brown-yellow to creamy-white and resemble a sea sponge or head of cauliflower. They are round and range from 10 cm to 50cm in diameter. They are considered parasites or 'saprobes' as they derive their nutrients from trees.",
                            Difficulty = "3",
                            Edible = true,
                            EdibleDesc = "Brittle, semi-firm and chewy consistency. Very similar to egg noodles which makes them great for soups! Medicinally, the dry weight of the fruiting body was found to contain up to 43.6% beta-glucan which is approved for treatment of cancer. Sparassis also has strong anti-inflammatory, anti-tumor, anti-diabetic, and neuro/cardio protection properties.",
                            Found = false,
                            Habitat = "Found at the base of hardwood trees such as: fir, pine, oak and spruce.",
                            Hint = "Look at the base of hardwoods where the sun can reach the forest floor but is partially shaded.",
                            History = "In Japan, Cauliflower mushrooms are known as Hanabiratake and have been utilized for both edible and medicinal purposes since ancient times.",
                            Latin = "Sparassis Crispa",
                            Name = "Cauliflower Mushroom",
                            Picture = "../assets/img/forest_mushroom_3_cauliflower.jpg",
                            Score = 100,
                            Smell = "Earthy and Musky",
                            Symbolism = "",
                            Taste = "Nutty, Earthy and Savory. Notes of fennel and almond.",
                            Type = "Mushroom"
                        },
                        new
                        {
                            ItemId = 2,
                            Category = "Forest",
                            Description = "These iconic mushrooms are large, white-gilled and red-capped with bumpy white spots.",
                            Difficulty = "1",
                            Edible = false,
                            EdibleDesc = "Not suitable for consumption",
                            Found = false,
                            Habitat = "Forms symbiotic relationships with many trees including pine, oak, spruce, fir, birch, and cedar. Although they require this relationship with trees, they grow from the soil and are not always right at the base of a tree. Unlike most mushrooms, Amanita Muscaria is tolerant to colder temperatures and thrives in the boreal region.",
                            Hint = "Check light soil terrain specifically around birch trees.",
                            History = "Although considered inedible due to a high level of toxins which cause gastrointestinal issues, they are noted for their hallucinogenic properties with the main psychoactive constituents being the neurotoxins ibotenic acid and muscimol. A local variety of the mushroom was used as an intoxicant and entheogen by the indigenous peoples of Siberia and by the Sámi, and has a religious significance in these cultures",
                            Latin = "Amanita Muscaria",
                            Name = "Fly Amanita",
                            Picture = "../assets/img/forest_mushroom_1_amanita.jpg",
                            Score = 25,
                            Smell = "Mild Earthiness",
                            Symbolism = "",
                            Taste = "Nutty and Slightly Buttery",
                            Type = "Mushroom"
                        },
                        new
                        {
                            ItemId = 3,
                            Category = "Forest",
                            Description = "These bright mushrooms are orange or yellow, very dense and meaty. Rather than gills, they have forked folds or ridges that run down the stipe, or stem, and have a smooth cap.",
                            Difficulty = "2",
                            Edible = true,
                            EdibleDesc = "Chanterelles are very meaty and hold their structure well which means they can be prepared in many ways without losing their integrity. Although they have a bit of a perppery flavor, they will absorb whichever flavors you cook them with. Simply sauteeing in butter is a forager's favorite way to prepare these mushrooms to really experience the natural flavor.",
                            Found = false,
                            Habitat = "Tend to grow in clusters in mossy coniferous forests, but are also often found in mountainous birch forests and among grasses and low-growing herbs. They love moisture, shade and an abundance of organic matter.",
                            Hint = "Look under leaves around douglas firs in late summer or early fall.",
                            History = "The name chanterelle originates from the Greek kantharos meaning tankard or cup",
                            Latin = "Cantharellus Cibarius",
                            Name = "Chanterelle",
                            Picture = "../assets/img/forest_mushroom_2_chanterelle.jpg",
                            Score = 50,
                            Smell = "Fruity and Apricot-like",
                            Symbolism = "Chanterelles have been eaten as early as the 16th century and their popularity amongst the nobility as the influence of French cuisine spread meant they became a Symbol of Wealth.",
                            Taste = "Mildly Peppery",
                            Type = "Mushroom"
                        },
                        new
                        {
                            ItemId = 4,
                            Category = "Coast",
                            Description = "This 'mushroom' is bright reddish-orange and is very firm and dense, with a pimpled 'cap'. It is often twisted into odd shapes and the inside is white. Contrary to its common name it is not a mushroom, but rather a parasitic ascomycete fungus that grows on milk cap mushrooms and russula mushrooms, turning them a reddish orange color that resembles the outer shell of a cooked lobster. Most milk caps and russulas are inedible in their natural form, so this ascomycete fungus turns the inedible to edible.",
                            Difficulty = "2",
                            Edible = true,
                            EdibleDesc = "Lobster mushrooms are incredibly dense and are best when cooked in smaller chunks. Unlike most mushrooms, lobsters have a strong, distinct seafood flavor. Because of this, they are often used in seafood dishes to enhance the flavor, rather than trying to infuse other flavor into the mushroom itself. Of course, sauteeing in butter will allow you to get the full flavor of the mushroom itself.",
                            Found = false,
                            Habitat = "Found in woods and forests in the coastal regions of the PNW. They are especially likely under hemlock trees, and usually appear in September or October. They may grow singly, in pairs or in clusters.",
                            Hint = "Don't be afraid to dig! If you see a mound of pine needles and dirt that looks out of place it's probably a lobster mushroom.",
                            History = "The name hypomyces is a Greek word meaning 'mushroom underneath'.",
                            Latin = "Hypomyces Lactifluorum",
                            Name = "Lobster Mushroom",
                            Picture = "../assets/img/forest_mushroom_2_lobster.jpg",
                            Score = 50,
                            Smell = "Shrimpy, Nutty, Slightly Sweet",
                            Symbolism = "",
                            Taste = "Seafood-like",
                            Type = "Mushroom"
                        },
                        new
                        {
                            ItemId = 5,
                            Category = "Forest",
                            Description = "Salmon Berry is a shrub growing to 3.5 to 13 feet tall and has pink, purple, or red flowers. It is known for its fruit, which bears resemblance to a raspberry.",
                            Difficulty = "easy",
                            Edible = true,
                            EdibleDesc = "Fruit is edible, but tastes bland",
                            Found = false,
                            Habitat = "Moist spots in and around woods",
                            Hint = "Lighter in color than Raspberries",
                            History = "The name of Salmonberry is believed to have originated from the natives' preference to eat them with salmon roe.",
                            Latin = "Rubus Spectabilis",
                            Name = "Salmon Berry",
                            Picture = "../assets/img/forest_flower_1_salmonberry.jpg",
                            Score = 25,
                            Smell = "",
                            Symbolism = "Holiness",
                            Taste = "Bland",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 6,
                            Category = "Forest",
                            Description = "Pacific bleeding heart is a perennial plant that grows from 10 - 20 inches tall. It has attractive blue-green lacy foliage and blooms delicate pink flowers in late spring. Its heart-shaped flowers grow in clusters and if deadheaded will continue to bloom through summer.",
                            Difficulty = "medium",
                            Edible = true,
                            EdibleDesc = "In the form of a root tincture or hot compress it can help pain relief, and can be applied externally to bruises and sprains. Internally, the tincture of bleeding heart can also help calm frazzled nerves especially after a frightening experience such as an accident or other trauma. The roots of this plant are generally gathered in summer and fall, up to the time when the leaves start to turn.",
                            Found = false,
                            Habitat = "damp soil with partial shade",
                            Hint = "Check near rivers and creeks",
                            History = "",
                            Latin = "Dicentra Formosa",
                            Name = "Bleeding Heart",
                            Picture = "../assets/img/forest_flower_2_bleedingheart.jpg",
                            Score = 50,
                            Smell = "",
                            Symbolism = "Romantic love and purity",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 7,
                            Category = "Forest",
                            Description = "Native to the forests of western North America, the orange Honeysuckle is a deciduous shrub that can shoot up to 20 fet tall and intertwine into the canopy of trees and other shrubs. ",
                            Difficulty = "medium",
                            Edible = true,
                            EdibleDesc = "They eventually give way to translucent, orange-red berries. The fruits are edible either raw or cooked.",
                            Found = false,
                            Habitat = "Dry to moderately moist forested thickets; north-facing slopes and streambanks.",
                            Hint = "Check near rivers and creeks",
                            History = "The tubular flowers are favorites for hummingbirds, as their beaks fit perfectly inside to get the nectar.",
                            Latin = "Lonicera Ciliosa",
                            Name = "Orange Honeysuckle",
                            Picture = "../assets/img/forest_flower_2_orangehoneysuckle.jpg",
                            Score = 50,
                            Smell = "Ravioli",
                            Symbolism = "Love, divination, luck",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 8,
                            Category = "Forest",
                            Description = "1 widely oval basal leaf on short petiole. Leaf 1–2 1/2 in. across at widest point, with parallel veins, emerging in autumn, persisting through winter, withering in summer. Flower consists of 3 showy, usually rosy pink, pointed sepals and 2 usually pink petals above large, hanging, white or lighter pink slipper with rose-madder spotting. Bracts wrapping stem 2–4, top bract erect above flower. Albinos are not rare.",
                            Difficulty = "hard",
                            Edible = false,
                            EdibleDesc = "This plant is endangered. Do not forrage. ",
                            Found = false,
                            Habitat = "Grows in deep forests in mountains around the world, below 5500 ft.",
                            Hint = "Calypso is Greek for she who conceals.",
                            History = "The genus is named for the beautiful sea nymph in Homer's Odyssey.",
                            Latin = "Calypso Bulbosa",
                            Name = "Calypso Orchid",
                            Picture = "../assets/img/forest_flower_3_calypsoorchid.jpg",
                            Score = 100,
                            Smell = "Ravioli",
                            Symbolism = "Love, divination, luck",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 9,
                            Category = "Forest",
                            Description = "Named for its hooded flowers, the columbian Mondshood's sepals resemble a monk's cowl.",
                            Difficulty = "easy",
                            Edible = false,
                            EdibleDesc = "This plant is considered to be poisonous",
                            Found = false,
                            Habitat = "Moist wet areas.",
                            Hint = "Blooms in summer.",
                            History = "",
                            Latin = "Aconitum columbianum",
                            Name = "Columbian Monkshood",
                            Picture = "../assets/img/forest_flower_1_columbianmonkshood.jpg",
                            Score = 25,
                            Smell = "Ravioli",
                            Symbolism = "Beware, a deadly foe is near",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 28,
                            Category = "Forest",
                            Description = "Huckleberry fruits are edible and resemble blueberries (Vaccinium species), to which they are closely related.",
                            Difficulty = "hard",
                            Edible = true,
                            EdibleDesc = "Berries are edible",
                            Found = false,
                            Habitat = "require acidic and moist but well-drained soil. Can only be found at elevations above 5,000 ft.",
                            Hint = "check in high places",
                            History = "Huckleberry plants can only grow in the wild",
                            Latin = "Vaccinium Corymbosum",
                            Name = "Huckle Berry",
                            Picture = "../assets/img/forest_flower_3_huckleberry.jpg",
                            Score = 100,
                            Smell = "Ravioli",
                            Symbolism = "",
                            Taste = "Better than blue berries",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 10,
                            Category = "Coast",
                            Description = "This is an herbaceous, perennial plant that produces one to several stems 8-40 inches in height. The leaves are cauline, and more or les clasping.",
                            Difficulty = "Easy",
                            Edible = true,
                            EdibleDesc = "The entire plant is reportedly edible and nutritious.",
                            Found = false,
                            Habitat = "It can grow from sea level to 3,500 m in elevation. It is frequently found in the mildly disturbed soil grasslands and open forests.",
                            Hint = "Look for well-drained soil, and open spaces where the flower can have full sun.",
                            History = "In antiquity, the plant was known as 'herba militaris' for its use in stanching the flow of blood from wounds. Other names implying its historical use in healing—particularly in the military—include bloodwort, knight's milfoil, staunchweed, and, from its use in the US Civil War, soldier's woundwort.",
                            Latin = "Achillea millefolium",
                            Name = "Common yarrow",
                            Picture = "../assets/img/coast_flower_1_common-yarrow.jpg",
                            Score = 10,
                            Smell = "Has a sweet scent similar to that of mums, so powerful that it may be irritating to some.",
                            Symbolism = "The name Achillea is derived from mythical Greek character Achilles, who reportedly carried it with his army to treat battle wounds.",
                            Taste = "Both its leaves and flowers are bitter and astringent.",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 11,
                            Category = "Coast",
                            Description = "1-2 foot perennial that quickly spreads by underground roots. The wooly flowers are actually flower heads of tiny disc flowers subtended by papery white bracts.",
                            Difficulty = "Medium",
                            Edible = true,
                            EdibleDesc = "The leaves and young plants are edible when cooked.",
                            Found = false,
                            Habitat = "Typically grows on dry, sandy or gravelly sites.",
                            Hint = "",
                            History = "The plant is dioecious, meaning the pollen-producing (male) and seed-producing (female) flowers are borne on separate plants.",
                            Latin = "Anaphalis margaritacea",
                            Name = "Pearly everlasting",
                            Picture = "../assets/img/coast_flower_2_pearly-everlasting.jpg",
                            Score = 30,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 12,
                            Category = "Coast",
                            Description = "It is a poisonous species of flowering plant in the plantain family Plantaginaceae",
                            Difficulty = "Medium",
                            Edible = false,
                            EdibleDesc = "Don't eat it, it is poisonous.",
                            Found = false,
                            Habitat = "Grows in acidic soils, in partial sunlight to deep shade.",
                            Hint = "Look for them in moorland and heath margins, sea-cliffs, rocky mountain slopes and hedge banks.",
                            History = "Due to the presence of the cardiac glycoside digitoxin, the leaves, flowers and seeds of this plant are all poisonous to humans and some animals and can be fatal if ingested.",
                            Latin = "Digitalis purpurea",
                            Name = "Foxglove",
                            Picture = "../assets/img/coast_flower_3_foxglove.jpg",
                            Score = 60,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 13,
                            Category = "Desert",
                            Description = "You’ll find these dime-sized flowers carpeting sagebrush flats. In particularly good wildflower seasons, that's no exaggeration--they truly carpet the ground.",
                            Difficulty = "easy",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "Meadow, Shrub-Steppe, Coastal",
                            Hint = "It grows from a small patch of somewhat fleshy leaves at the ground",
                            History = "",
                            Latin = "Crocidium multicaule",
                            Name = "Goldfields",
                            Picture = "../assets/img/Desert_flower_1_Goldfields.jpg",
                            Score = 15,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 14,
                            Category = "Desert",
                            Description = "Reminding us that nature is fragile, this early bloomer has a delicate, white to lavender-pink, irregular flower atop a slender red stem.",
                            Difficulty = "easy",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "grasslands, sagebrush plains, dry open areas, at low to high elevations",
                            Hint = "It has a somewhat sticky stem and each stem bears up to 14 flowers",
                            History = "",
                            Latin = "Lithophragma parviflorum",
                            Name = "Prairie Star",
                            Picture = "../assets/img/desert_flower_1_prairiestar.jpg",
                            Score = 20,
                            Smell = "fragrant",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 15,
                            Category = "Desert",
                            Description = "This low-growing flower prefers rocky crevices and exposed locations. These beauties always astound with their pop of color--flowers have 5 pink-purple-white petals. Adapted to extreme environments, cushion-like plants like phlox often have taproots 8-15’ deep!",
                            Difficulty = "easy",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "grasslands, sagebrush plains, dry open areas, at low to high elevations",
                            Hint = "The blossoms are so profuse that they literally cover the evergreen foliage of narrow, needle-like, bright green leaves.",
                            History = "",
                            Latin = "Phlox diffusa",
                            Name = "Spreading Phlox",
                            Picture = "../assets/img/desert_flower_1_spreadingphlox.jpg",
                            Score = 25,
                            Smell = "fragrant",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 16,
                            Category = "Desert",
                            Description = "Sand lilies can often look like bunches of tissue paper dotting your view. It grows in rosette-like bunches with 4-8 white flowers per bunch.",
                            Difficulty = "medium",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "sandy or rocky areas",
                            Hint = "Blooms & leaves might be nipped off, as it is a favorite snack of rabbits and deers!",
                            History = "",
                            Latin = "Leucocrinum monatanum",
                            Name = "Sand Lily",
                            Picture = "../assets/img/desert_flower_2_sandlily.jpg",
                            Score = 50,
                            Smell = "fragrant",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 17,
                            Category = "Desert",
                            Description = "Perhaps one of our most unusual lilies, the spotted fritillary is brown to greenish in color with yellow, red, or white markings. They can be hard to spot because of their subdued color!",
                            Difficulty = "medium",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "grasslands or Cascade foothill forests",
                            Hint = "Flowers hang downward or facing outward and 1-3 blooms can be found per stalk.",
                            History = "",
                            Latin = "Fritillaria atropurpurea",
                            Name = "Spotted Fritillary",
                            Picture = "../assets/img/desert_flower_2_spottedfritillary.jpg",
                            Score = 65,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 18,
                            Category = "Desert",
                            Description = "This bloom is easy to miss with its nodding, muted flowerheads. This generalist wildflower that attracts all sorts of flies, wasps, and other insects for pollination has an interesting feature that might not be seen at first glance.",
                            Difficulty = "medium",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = " It thrives in fir and aspen woods, but can also be found in Central Oregon’s ponderosa pine forests and dry sagebrush deserts.",
                            Hint = "Leaves are divided with rounded tips. Flower is clustered at the stem top and hangs down.",
                            History = "Unusual for peonies, Brown’s peony has floral nectar, which is a critical food source for native pollinators in early spring when there aren’t many food options.",
                            Latin = "Paeonia brownii",
                            Name = "Brown’s peony",
                            Picture = "../assets/img/desert_flower_2_brownspeony.jpg",
                            Score = 75,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 19,
                            Category = "Desert",
                            Description = "Bradshaw's desert parsley is a low, more or less erect perennial species that grows from a long slender taproot.",
                            Difficulty = "hard",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "wet prairie habitats in clay soils or substrates having a dense clay layer below the surface",
                            Hint = "Species is flowering from mid April through May.",
                            History = "It was thought to be extinct until 1979, when it was rediscovered by a University of Oregon graduate. This herb was common in the Willamette Valley before agricultural development and fire prevention which has allowed shrubs and weeds to invade. In 2021, it was taken off the endangered species list.",
                            Latin = "Lomatium bradshawii",
                            Name = "Bradshaw's desert parsley",
                            Picture = "../assets/img/desert_flower_3_bradshawsdesertparsley.jpg",
                            Score = 100,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 20,
                            Category = "Desert",
                            Description = "The flower looks like a bulbous lantern. These flowers are usually in groups of three on nodding stems. The sepals of the plant (the part that supports the petals in bloom and is often green) are fused together to form a cup (or bulbous lantern!) with tips curving outwards.",
                            Difficulty = "hard",
                            Edible = true,
                            EdibleDesc = "Native Americans used this plant for medicinal purposes",
                            Found = false,
                            Habitat = "dry meadows, pine forests, and sagebrush desert",
                            Hint = "After pollination the stems slowly turn upright, so that by the time the tufted fruit appear the feathery heads look like smoke wafting away from the plant – or something like the little “troll” dolls that once were so popular",
                            History = "It was thought to be extinct until 1979, when it was rediscovered by a University of Oregon graduate. This herb was common in the Willamette Valley before agricultural development and fire prevention which has allowed shrubs and weeds to invade. In 2021, it was taken off the endangered species list.",
                            Latin = "Geum triflorum",
                            Name = "Prairie smoke",
                            Picture = "../assets/img/desert_flower_3_prairiesmoke.jpg",
                            Score = 85,
                            Smell = "",
                            Symbolism = "Prairie smoke is an essence for softening excessive personal boundaries. It finds and brings forth softness, a yielding quality, and a feeling of acceptance of however small or fragile we may feel we are.",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 21,
                            Category = "Desert",
                            Description = "What an unusual flower shape! I’m guessing that when you were a child and drew a flower, the petals did not look like this (or maybe you were a terrible artist like me and they DID look like a ragged robin!)",
                            Difficulty = "hard",
                            Edible = false,
                            EdibleDesc = "",
                            Found = false,
                            Habitat = "rocky, sandy locations",
                            Hint = "Ragged robin has pink petals that are divided into three lobes with the central lobe wider than the other two.",
                            History = "It was described by Meriwether Lewis close to Kamiah, Idaho during the Lewis and Clark Expedition and it was subsequently brought back as a botanical specimen. The discovery was first described on May 28, 1806, by William Clark and subsequently by Lewis on June 1 of that year.",
                            Latin = "Clarkia pulchella",
                            Name = "Ragged robin",
                            Picture = "../assets/img/desert_flower_3_raggedrobin.jpg",
                            Score = 85,
                            Smell = "",
                            Symbolism = "",
                            Taste = "",
                            Type = "Flower"
                        },
                        new
                        {
                            ItemId = 22,
                            Category = "Desert",
                            Description = "Rabbitbrush can grow 5-7 feet tall. It has flower heads that consist of small, yellow, tubular flowers arranged in dense clusters. Rabbitbrush's presence might help reduce the severity of weed invasions, using its deep roots and large amounts of leaf litter to outcompete invasive weeds. ",
                            Difficulty = "easy",
                            Edible = true,
                            EdibleDesc = "A decoction of the twigs has been used in the treatment of toothaches, coughs and chest pains. An infusion of the flowering stems has been used in the treatment of colds and TB. An infusion of the leaves and stems has been used to treat colds, diarrhoea, stomach cramps, etc. It has also been used externally as a wash for sores and skin eruptions, especially smallpox. The plant shows slight bactericidal activity.",
                            Found = false,
                            Habitat = "open lands and in east-side forests.",
                            Hint = "Flowers bloom from August to October as other plants are fading, providing vivid color and a pollen source for insects late in the summer. ",
                            History = "Native Americans reportedly used rabbitbrush as a yellow dye, to make a medicinal tea, and for chewing gum. Rabbitbrush was first tested as a source of high quality rubber during World War II. In recent decades, there has been renewed interest in its potential for production of rubber, resins, and other chemicals. Compounds in rubber rabbitbrush are being evaluated for nematocides, anti-malarial properties, and insect repellents. Rubber rabbitbrush has also been identified as a potential source of biomass and biocrude fuels.",
                            Latin = "Ericameria nauseosa",
                            Name = "Gray rabbitbrush",
                            Picture = "../assets/img/../assets/img/desert_tree_1_grayrabbitbrush.jpg",
                            Score = 25,
                            Smell = "pungent/pineapple-like flowers",
                            Symbolism = "",
                            Taste = "bitter",
                            Type = "Tree"
                        },
                        new
                        {
                            ItemId = 23,
                            Category = "Desert",
                            Description = "This shrub grows 3-6 1/2 feet tall with a thick, woody trunk. Leaves are gray-green, evergreen, and soft. They have 3 lobes on a wide tip.",
                            Difficulty = "easy",
                            Edible = true,
                            EdibleDesc = "Sagebrush can be used in preparing a lot of dishes. These dishes may include drinks such as those which various fruits in them. Mostly cocktails are made with the help of sage brush as a good additive in the form of a flavor booster. The Native Americans used to make flour from the seeds of sagebrush which would later on become a normal part of their day to day diet.",
                            Found = false,
                            Habitat = "arid and semi-arid conditions, throughout a range of cold desert, steppe, and mountain habitats.",
                            Hint = "Flowers are quite small and yellow with hairy stems.",
                            History = "Native Americans used to make pastes and salves out of sage brush to treat various wounds and other injuries. Some Native American nations even used sagebrush to treat to headaches. Others would use it for getting rid of pain in various parts of the body. When a sagebrush plant is attacked by predators like insects, the plant emits volatile organic compounds that neighboring sagebrush plants can sense and react to by producing defensive chemicals that make them unattractive, or even poisonous, to the attackers.  And other plants, like wild tobacco, can eavesdrop on this and ramp up their own defenses, significantly lowering damage from feeding animals. ",
                            Latin = "Artemisia tridentata",
                            Name = "Big Sagebrush",
                            Picture = "../assets/img/../assets/img/desert_tree_1_bigsagebrush.jpg",
                            Score = 15,
                            Smell = " strong turpentine-like odor, especially when wet",
                            Symbolism = "Native Americans use Sagebrush or purification of body and soul, as a smoke during the ritual sweat lodges, and as a smudge to clear the energy of a room or environment.",
                            Taste = "bitter",
                            Type = "Tree"
                        },
                        new
                        {
                            ItemId = 24,
                            Category = "Desert",
                            Description = "Ponderosa pines are a very common evergreen in Central Oregon. The bark helps to distinguish it from other species. Mature to over-mature individuals have yellow to orange-red bark in broad to very broad plates with black crevices. Younger trees have blackish-brown bark, referred to as blackjacks by early loggers.",
                            Difficulty = "easy",
                            Edible = true,
                            EdibleDesc = "Native Americans consumed the seeds and sweet inner bark. They chewed the dried pitch, which was also used as a salve. The needles were also boiled into a solution to treat coughs and fevers.",
                            Found = false,
                            Habitat = "dry forest lands",
                            Hint = "If you smell the deep furrows in the bark, it often smells like butterscotch or vanilla.",
                            History = "Native Americans used the limbs and branches as firewood and building material, and the trunks were carved into canoes. The needles and roots were made into baskets. In the 19th and 20th centuries, old-growth trees were widely used by settlers as lumber, including for railroads.",
                            Latin = "Pinus ponderosa",
                            Name = "Ponderosa Pine",
                            Picture = "../assets/img/desert_tree_1_ponderosapine.jpg",
                            Score = 15,
                            Smell = "pine",
                            Symbolism = "For Native Americans, they represent wisdom and longevity. To other cultures, they represent fertility and life. ",
                            Taste = "herbal, sweet, a little perfumey",
                            Type = "Tree"
                        },
                        new
                        {
                            ItemId = 25,
                            Category = "Desert",
                            Description = "Old-growth western junipers (Juniperus occidentalis) are stooped and twisted, their furrowed red bark typically blanketed in lichen. ",
                            Difficulty = "medium",
                            Edible = true,
                            EdibleDesc = "Fruit - raw or cooked. A thin dry flesh with a resinous flavour. The fruit is sweet and nutritious, it can also be dried or ground into a powder and mixed with cereal flours to be made into a bread.The cones are about 10mm in diameter, they take 2 years to mature.",
                            Found = false,
                            Habitat = "Usually found on thin rocky or sandy soils on desert foothills and lower mountains, also on windswept peaks up to elevations of 3,000 metres where they become low gnarled shrubs.",
                            Hint = "Juniperus occidentalis is a shrub or small tree 4–15 meters (13–49 ft) tall. Exceptionally tall specimens can be found in the John Day area of Oregon in excess of 26–28 m (85–92 ft) tall.",
                            History = "Western juniper was quite widely employed as a medicinal herb by a number of native North American tribes who used it to treat a variety of complaints, especially those related to the kidneys and the skin.",
                            Latin = "Juniperus occidentalis",
                            Name = "Western Junipers",
                            Picture = "../assets/img/../assets/img/desert_tree_2_westernjunipers.jpg",
                            Score = 60,
                            Smell = "",
                            Symbolism = "John Michael Greer in the Encyclopedia of Natural Magic suggests that Juniper is tied to the element of fire, with its astrological aspects being Mars in Aries (can’t get much more fiery than that!) ",
                            Taste = "resinous, sweet",
                            Type = "Tree"
                        },
                        new
                        {
                            ItemId = 26,
                            Category = "Desert",
                            Description = "A VERY fragrant shrub (your nose will alert you to its presence!). Snowbrush has stout stems that are many branched, growing 3-11 feet tall. It has 1-3 inch shiny evergreen leaves that are widely oval and finely toothed. Flowers are white in thick rounded clusters near the tops of stems.",
                            Difficulty = "medium",
                            Edible = true,
                            EdibleDesc = "The dried leaves make a pleasant tasting, astringent tea that can be used as a caffeine-free black tea substitute. Kootenai tribes used the tea to treat tuberculosis.  Other native tribes used a decoction of leaves for eczema, dandruff, and arthritis.",
                            Found = false,
                            Habitat = "Moist to dry open forests, brushy sites, rocky slopes, and recently burned or disturbed areas such as roadsides and logged areas at low to subalpine elevations.",
                            Hint = "Often grows in dense patches in open areas.",
                            History = "Their seeds can remain buried for over 200 years before sprouting. Snowbrush is beneficial to bees and butterflies, and is a host plant for California tortoiseshells, pale tiger swallowtails, and spring azures, among others. Saponins, foam-producing compounds, in the flowers also make it useful for soap.",
                            Latin = "Ceanothus velutinus",
                            Name = "Snowbrush",
                            Picture = "../assets/img/../assets/img/desert_tree_2_snowbrush.jpg",
                            Score = 45,
                            Smell = "heavy, spicy-resinous fragrance",
                            Symbolism = "",
                            Taste = "astringent",
                            Type = "Tree"
                        },
                        new
                        {
                            ItemId = 27,
                            Category = "Desert",
                            Description = "A fir native to the Pacific Northwest and Northern California of North America, occurring at altitudes of sea level to 1,700 metres (5,600 ft). It is a major constituent of the Grand Fir/Douglas Fir Ecoregion of the Cascade Range. The tree typically grows to 40–70 m (130–230 ft) in height, and may be the tallest Abies species in the world. There are two varieties, the taller coast grand fir, found west of the Cascade Mountains, and the shorter interior grand fir, found east of the Cascades.",
                            Difficulty = "hard",
                            Edible = true,
                            EdibleDesc = "Grand fir needles were traditionally used by West Coast First Nations as a flavour agent for food and as a medicinal herb.",
                            Found = false,
                            Habitat = "The grand fir grows along the coast from southwest British Columbia to Northern California, with the inland variety growing in eastern areas of Washington and Oregon, and the Idaho Panhandle. It can be found growing at elevations of up to 1,700 m (5,600 ft)",
                            Hint = "All firs are easily recognized by the smooth bark on young twigs and small, round leaf scars left by dropped needles. Grand Fir is most easily recognized by its long needles borne horizontally on opposite sides of the twigs.  The entire branch will appear flattened so that it has distinct upper and lower sides.",
                            History = "It was first described in 1831 by David Douglas. It is closely related to white fir. The bark was historically believed to have medicinal properties, and it is popular in the United States as a Christmas tree. Its lumber is a softwood, and it is harvested as a hem fir.",
                            Latin = "Abies grandis",
                            Name = "Grand Fir",
                            Picture = "../assets/img/../assets/img/desert_tree_3_grandfir.jpg",
                            Score = 65,
                            Smell = "pine scent",
                            Symbolism = "Fir trees symbolize determination, honesty, and the endurance that comes with hope for the future.",
                            Taste = "Edible conifer flavours range from citrusy lemon and bitter grapefruit to herbaceous rosemary and woodsy pine",
                            Type = "Tree"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
